[info]
id = "rust" # dvs id

[container]
workspace = "/project" # -w
mount_pwd = "/project" # --mount type=bind,source="$(pwd)",target=/project
mounts = ["$HOME/.cargo/registry:/usr/local/cargo/registry"] # --mount type=bind,source=$HOME/.cargo/registry,target=/usr/local/cargo/registry
env = ["CARGO_TARGET_DIR=/target"] # -e CARGO_TARGET_DIR=/target

[image]
default = "latest"
versions = [
    "latest",
    "alpine",
    "bookworm",
    "bullseye",
    "buster",
    "slim",
    "slim-bookworm",
    "slim-bullseye",
    "slim-buster",
]
pull = "rust" # Applies to all image unless overridden
pull_updates = true
entrypoint = "/bin/sh"
cmd = "-c /bin/bash"

[image.alpine]
entrypoint = "/bin/sh"
cmd = "-c /bin/sh"
